
optimizer:
  name: adam
  params:
    learning_rate: 0.01

loss: "categorical_crossentropy"
metrics: ["accuracy"]
epochs: 10
callbacks:
  - name: early_stopping
    params:
      monitor: val_loss
      patience: 1
  - name: model_checkpoint
    params:
      monitor: val_accuracy
      save_best_only: true
