services:
  tensorflow-ngc-2402:
    container_name: tensorflow-ngc-2402

    build: .
    image: tensorflow-ngc-2402
    
    ipc: host
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all #device_ids: ['0']
              capabilities: [gpu]

    volumes:
      - .:/workspace

    command: python3 train.py
