model_name: "CNN_with_VGG16_transfer_learning"

builder_name: "declarative_builder"
blocks:

  - name: backbone
    type: vgg16_backbone
    params: {trainable_blocks: [block5], target_size: [224,224], weights: imagenet, include_top: false}

  - name: head
    type: dense_head
    params: {units: [1000, 200], hidden_activation: relu, output_activation: softmax, batch_norm: false, dropout_rate: 0.3}
    inject_num_classes_as: num_classes