model_name: "CNN_from_Scratch"

builder_name: "declarative_builder"
blocks:

  - name: conv1_1
    type: conv2d
    params: {filters: 32, kernel_size: [3,3], strides: [1,1], padding: same, activation: relu, batch_norm: true}

  - name: conv1_2
    type: conv2d
    params: {filters: 32, kernel_size: [3,3], strides: [1,1], padding: same, activation: relu, batch_norm: true, pooling: max2d, pool_size: [2,2], dropout_rate: 0.25}

  - name: conv2_1
    type: conv2d
    params: {filters: 64, kernel_size: [3,3], strides: [1,1], padding: same, activation: relu, batch_norm: true}

  - name: conv2_2
    type: conv2d
    params: {filters: 64, kernel_size: [3,3], strides: [1,1], padding: same, activation: relu, batch_norm: true, pooling: max2d, pool_size: [2,2], dropout_rate: 0.25}

  - name: head
    type: dense_head
    params: {units: [512], hidden_activation: relu, output_activation: softmax, batch_norm: true, dropout_rate: 0.5}
    inject_num_classes_as: num_classes
