task: ${task}

dataset_name: "PNOA_ortoimagenes"

root_dir: "raw_data/classification/multiclass"
train_dir: "${dataset.root_dir}/Train"
test_dir: "${dataset.root_dir}/Test"
metadata_csv: "${dataset.root_dir}/metadata.csv"

num_bands: 4

loader: 
  name: "from_local_directory"
  params:
    batch_size: 32
    image_size: [32, 32]
    validation_split: 0.2
    label_mode: "categorical"
    seed: ${global_seed}
    shuffle: True
    
preprocessing:
  enabled: true
  steps:
    - name: "pixel_value_normalization"
      params:
        value: 255.0

augmentation:
  enabled: true
  transforms:
    - name: "random_flip"
      params:
        mode: "horizontal_and_vertical"
    
    - name: "random_rotation"
      params:
        factor: 0.25

    - name: "random_zoom"
      params:
        height_factor: 0.05
        width_factor: 0.05
    
    - name: "random_translation"
      params:
        height_factor: 0.05
        width_factor: 0.05
