
dataset_name: "PNOA-ortoimagenes"
num_bands: 4
train_dir: "raw_data/Train"
test_dir: "raw_data/Test"

loader: 
  name: "from_local_directory"
  params:
    batch_size: 32
    image_size: [32, 32]
    validation_split: 0.2
    label_mode: "categorical"
    seed: 1
    shuffle: True
    
preprocessing:
  steps:
    - name: "pixel-value-normalization"
      params:
        value: 255.0

augmentation:
  enabled: true
  transforms:
    - name: "random-flip"
      params:
        mode: "horizontal_and_vertical"
    
    - name: "random-rotation"
      params:
        factor: 0.25

    - name: "random-zoom"
      params:
        height_factor: 0.05
        width_factor: 0.05
    
    - name: "random-translation"
      params:
        height_factor: 0.05
        width_factor: 0.05
