
dataset_name: "PNOA-ortoimagenes"
loader: "from_local_directory"
train_dir: "data/Train"
test_dir: "data/Test"
num_bands: 4
image_size: [32, 32]
batch_size: 32
label_mode: "categorical"
validation_split: 0.2
shuffle: True
seed: 1
preprocessing:
    steps:
        - "pixel-value-normalization"
