epochs: 10

metrics: ["accuracy"]

loss:
  name: categorical-crossentropy
  params:
    from_logits: false
    label_smoothing: 0.0

optimizer:
  name: adam
  params:
    learning_rate: 0.001

callbacks:
  - name: early_stopping
    params:
      monitor: val_loss
      patience: 1
  - name: model_checkpoint
    params:
      monitor: val_accuracy
      save_best_only: true

verbose: 1
